# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e613a3e17e8f36c8aaa27d81be18d7b2bff49c50be525c93e3f187c215f7bcb375449a436186a8dff603761461d2912188cea43b150b295456f233d11668033a

test:
  secret_key_base: d7184c2f59de8c8136f338fdf95783d14518d26df4e3dbaef8d9b0edc84e72a096aa1e9b3a14e0c40a7c49c334ba216760e3b2b18260c05dd93c7647de3ee9f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
